// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSbAyckd6g2cpEjQJ5rYH-a6M1tGkHI3E',
    appId: '1:287697892985:web:d6f4d5db639993f4efc6a8',
    messagingSenderId: '287697892985',
    projectId: 'seesay',
    authDomain: 'seesay.firebaseapp.com',
    databaseURL:
        'https://seesay-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'seesay.appspot.com',
    measurementId: 'G-MRNBN6NFRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChgx1_1AlmpykEa4ljMSqPDKNkCFGg544',
    appId: '1:287697892985:android:dd8bb28d9569cee8efc6a8',
    messagingSenderId: '287697892985',
    projectId: 'seesay',
    databaseURL:
        'https://seesay-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'seesay.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA78kg9Ip2gIdl5rdccicoLNNvtztNZiys',
    appId: '1:287697892985:ios:0d1c7cf4801349b0efc6a8',
    messagingSenderId: '287697892985',
    projectId: 'seesay',
    databaseURL:
        'https://seesay-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'seesay.appspot.com',
    iosClientId:
        '287697892985-sbmaaoppq7ptne802n8m7p0cjgkq2no6.apps.googleusercontent.com',
    iosBundleId: 'com.example.seesay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA78kg9Ip2gIdl5rdccicoLNNvtztNZiys',
    appId: '1:287697892985:ios:0d1c7cf4801349b0efc6a8',
    messagingSenderId: '287697892985',
    projectId: 'seesay',
    databaseURL:
        'https://seesay-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'seesay.appspot.com',
    iosClientId:
        '287697892985-sbmaaoppq7ptne802n8m7p0cjgkq2no6.apps.googleusercontent.com',
    iosBundleId: 'com.example.seesay',
  );
}
