// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKAEbipS1WWzaQOWpwO5PI5ZlRK1WhG-M',
    appId: '1:752960257037:web:2cb25ad3434128f48ea944',
    messagingSenderId: '752960257037',
    projectId: 'logintest-fcb27',
    authDomain: 'logintest-fcb27.firebaseapp.com',
    storageBucket: 'logintest-fcb27.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxNi3b5BT9OfVBgF2JJk6jTdpFPzbHYuk',
    appId: '1:752960257037:android:649987284f20a7a38ea944',
    messagingSenderId: '752960257037',
    projectId: 'logintest-fcb27',
    storageBucket: 'logintest-fcb27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb-1L1HRz10Je6SA6WApYmnnpTAI0k5mc',
    appId: '1:752960257037:ios:d74048ab524a78678ea944',
    messagingSenderId: '752960257037',
    projectId: 'logintest-fcb27',
    storageBucket: 'logintest-fcb27.appspot.com',
    iosClientId: '752960257037-i12d026jgn5s3p5dao91dfju171se0v5.apps.googleusercontent.com',
    iosBundleId: 'com.example.seesay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb-1L1HRz10Je6SA6WApYmnnpTAI0k5mc',
    appId: '1:752960257037:ios:d74048ab524a78678ea944',
    messagingSenderId: '752960257037',
    projectId: 'logintest-fcb27',
    storageBucket: 'logintest-fcb27.appspot.com',
    iosClientId: '752960257037-i12d026jgn5s3p5dao91dfju171se0v5.apps.googleusercontent.com',
    iosBundleId: 'com.example.seesay',
  );
}
